# Generated by Django 5.0.9 on 2024-12-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_content_remove_post_dislikes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='synopsis',
            new_name='content',
        ),
    ]
